version: "3"
services: 
  mysql:
    ports:
      - '3308:3306'
  nginx:
    ports: 
      - "3000:80"
  needle-blog:
    build: .
    environment: 
      - NODE_ENV=development
    command: 
      sh ./start.sh