version: "3"
services: 
  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  needle-blog:
    build: .
    volumes: 
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment: 
      - PORT=3000
networks: 
  default:
    external: true
    name: needle_blog_bridge

