version: "3"
services:
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports: 
      - "80:80"
  backend:
    build: ./backend
    depends_on: 
      - mysql
    restart: always
    ports: 
      - "3000:3000"
    volumes: 
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - .env
    environment: 
      - PORT=3000