version: "3"
services: 
  nginx:
    ports: 
      - "80:80"
  needle-blog:
    build: .
    environment: 
      - NODE_ENV=production
    command: sh -c "node ./script/dbInit.js && npm run start:prod"