version: "3"
services: 
  mysql:
    ports:
      - '3307:3306'
  nginx:
    ports: 
      - "80:80"
  needle-blog:
    build: .
    scale: 2
    environment: 
      - NODE_ENV=production
    command: 
      sh ./start.sh