version: "3"
services:
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"
    env_file:
      - .env
  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  needle-blog:
    build: .
    depends_on: 
      - mysql
    restart: always
    volumes: 
      - /app/node_modules
    env_file:
      - .env
    environment: 
      - PORT=3000